name: rmd
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
    - torch>=2.0.0
    - numpy>=1.24.0
    - scipy>=1.10.0
    - mdanalysis>=2.4.0
    - mdtraj>=1.9.7
    - biopython>=1.81
    - matplotlib>=3.7.0
    - tqdm>=4.65.0
    - scikit-learn>=1.2.0
    - plotly>=5.14.0
    - seaborn>=0.12.0
    - pytest>=7.3.0
    - pytest-cov>=4.1.0
    - black>=23.3.0
    - flake8>=6.0.0
    - mypy>=1.3.0
